### ISSUE TITLE
When tokenizing a malformed card number an api level error is raised

### ISSUE THREAD

**Issue by scottbartell** [plated/vantiv-ruby#49]
When tokenizing by direct post, if a card number is too short or too long Vantiv responds with an XML parse error. This is unexpected because when a card number is the appropriate length but invalid, Vantiv responds differently.

Example response with a short or long credit card number:

``` json
{
  "litleOnlineResponse": {
    "@version": "10.3",
    "@response": "1",
    "@message": "Error validating xml data against the schema on line 1\nthe length of the value is 5, but the required minimum is 13."
  },
  "RequestID": "bla"
}
```

Example response with an invalid card number having the appropriate length:

``` json
{
  "litleOnlineResponse": {
    "@version": "10.2",
    "@response": "0",
    "@message": "Valid Format",
    "registerTokenResponse": {
      "@id": "bla",
      "@reportGroup": "1",
      "response": "820",
      "responseTime": "2016-06-01T20:06:18",
      "message": "Credit card number was invalid",
      "TransactionID": "foo"
    }
  },
  "RequestID": "bar"
}
```

Also, the response (`TokenizationResponse`) defines a method `invalid_card_number?` which returns false for cards that are malformed which can be misleading.

What do we want to do for this case?

**Comment by joshuaballoch** [comment]
I have two thoughts so far: 

1. I think partially this is a DevHub responsibility, to parse and standardize its responses. However, I think they think it's a API client responsibility, as they probably specify in their documentation that requests must follow certain request body format rules. I'm certain there is one in their saying that the credit card number field must be 13 characters or longer.
1. Given that, maybe it's a gem user responsibility. We make it a rule that the gem user needs to validate card number lengths before submission.

Still, I guess the argument could be made that it's a gem responsibility. I suppose you could change the gem to validate the field length before sending an API request to Vantiv, and have something like a `PreFlightResponse` that follows the `LiveTransactionResponse` and `TiedTransactionResponse` duck type, and responds to `credit_card_number_invalid?`.

That said, maybe it is worth it to see what happens in the eProtect iframe when you put a credit card number that is too short. Could be a way to see what their real opinion on this matter is. IE: does the eProtect form validate field length before making a request to Litle? If so, then i think for consistency, it should be the gem user's responsibility to validate that. If it does not, and it makes a request to Litle, and they handle a too-short card number in one endpoint, then maybe there is a case to be made to the Vantiv folks to also allow too-short card numbers on the direct tokenization endpoints.

Thoughts?

**Comment by scottbartell** [comment]
Closing this because we have migrated to Vantiv's XML API and this no longer applies.
